KAN-3. First try.
darcy3812/meme-game pull request #11
Opened 2024-08-25 13:42 UTC by youngbabybye

Hi. I'm your frontend developer. Can you please see the execution of task KAN-3? I've made some changes.

2024-09-06 15:30 UTC, darcy3812 requested changes

2024-09-06 15:30 UTC, darcy3812 commented on MemeGame/meme-front/src/Login.css
Убери лишние стили

2024-09-06 15:30 UTC, darcy3812 commented on MemeGame/meme-front/tailwind.config.js
Сам разобрался или скопировал? Если сам, то молодец
+1 чашка кофе

2024-09-06 15:32 UTC, youngbabybye commented on MemeGame/meme-front/src/Login.css
Убрать файл login.css ?

2024-09-06 15:32 UTC, youngbabybye commented on MemeGame/meme-front/tailwind.config.js
Сам разобрался с добавлением кастомных. Спасибо.

2024-09-07 11:46 UTC, darcy3812 commented on MemeGame/meme-front/src/Login.css
Если он не используется, то да

2024-09-07 12:58 UTC, darcy3812 requested changes

2024-09-07 12:58 UTC, darcy3812 commented on MemeGame/meme-front/src/Login.jsx
> +            <div className="flex p-5 font-boom font-black text-big text-center justify-center bg-cyan-400 bg-clip-text text-transparent">
надо бы добавить `cursor-default`

2024-09-07 12:58 UTC, darcy3812 commented on MemeGame/meme-front/src/index.css
надо бы добавить какой-то цвет для backgound-color, а то сейчас очень ярко

2024-09-07 16:25 UTC, merged